const APP={version:1,rangeEnd:'2028-07-20',debts:[['Akbank Kredi Kartı','Kredi Kartı',783548],['Ziraat Kredi Kartı','Kredi Kartı',750000],['Akbank Artı Hesap','Ek Hesap',64397.92],['Fiba Ek Hesap','Ek Hesap',250000],['Şekerbank Ek Hesap','Ek Hesap',100000],['VakıfBank Ek Hesap','Ek Hesap',175000],['Yapı Kredi Ek Hesap','Ek Hesap',400000],['Akbank Kredi','Kredi',517000],['Fiba Krediler','Kredi',1150000],['Şekerbank Kredi','Kredi',1448000],['VakıfBank Krediler','Kredi',2900000]],once:[['fiba-ek','Fiba Ek Hesap','Ek Hesap','2026-08-01',250000],['seker-ek','Şekerbank Ek Hesap','Ek Hesap','2026-08-01',100000],['vakif-ek','VakıfBank Ek Hesap','Ek Hesap','2026-08-01',175000],['yapi-ek','Yapı Kredi Ek Hesap','Ek Hesap','2026-08-01',400000],['akbank-kk','Akbank Kredi Kartı','Kredi Kartı','2026-08-05',783548],['ziraat-kk','Ziraat Kredi Kartı','Kredi Kartı','2026-08-12',750000],['akbank-ek','Akbank Artı Hesap','Ek Hesap','2026-08-16',64397.92],['fiba1','Fiba Kredi 1','Kredi','2026-08-30',218653.37],['fiba2a','Fiba Kredi 2','Kredi','2026-08-14',122725.94],['fiba2b','Fiba Kredi 2','Kredi','2026-09-14',122725.94],['fiba3a','Fiba Kredi 3','Kredi','2026-08-20',312727.51],['fiba3b','Fiba Kredi 3','Kredi','2026-09-20',312727.51],['zonex1','Zonex Çek','Çek','2026-08-04',350000],['zonex2','Zonex Çek','Çek','2026-08-11',1000000],['vitlo','Vitlo Çek','Çek','2026-08-11',750000],['avens1','Avens Çek','Çek','2026-08-25',490000],['avens2','Avens Çek','Çek','2026-09-29',510000],['avens3','Avens Çek','Çek','2026-10-27',1000000],['seker0','Şekerbank Kredi','Kredi','2026-08-17',128315]],recur:[['akbank-kredi','Akbank Kredi','Kredi','2026-08-22',22,64784,11],['vakif1','VakıfBank Kredi 1','Kredi','2026-08-29',29,135586,12],['vakif2','VakıfBank Kredi 2','Kredi','2026-08-20',20,101000,24],['seker','Şekerbank Kredi','Kredi','2026-09-15',15,128315,14],['kira','Dükkan Kira','Aylık Gider','2026-08-01',1,38000,0,'2028-07-01'],['dukkan-aidat','Dükkan Aidat','Aylık Gider','2026-08-01',1,750,0,'2028-07-01'],['kickboks','Kickboks Aidat','Aylık Gider','2026-08-01',1,15000,0,'2028-07-01'],['burs','Burs','Aylık Gider','2026-08-01',1,20000,0,'2028-07-01'],['duygu1','Duygu Maaş','Aylık Gider','2026-08-01',1,100000,0,'2028-07-01'],['duygu2','Duygu Maaş','Aylık Gider','2026-08-12',12,150000,0,'2028-07-12'],['alev','Alev Abla Maaş','Aylık Gider','2026-08-12',12,28000,0,'2028-07-12']]};
const KEY='metin_finans_state_v1';
const tl=new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY',minimumFractionDigits:2});
const fd=new Intl.DateTimeFormat('tr-TR',{day:'2-digit',month:'2-digit',year:'numeric'});
const fm=new Intl.DateTimeFormat('tr-TR',{month:'long',year:'numeric'});
const fms=new Intl.DateTimeFormat('tr-TR',{month:'short',year:'2-digit'});
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const parse=s=>{const[y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
function plusMonth(d,n,day){const x=new Date(d.getFullYear(),d.getMonth()+n,1),last=new Date(x.getFullYear(),x.getMonth()+1,0).getDate();x.setDate(Math.min(day,last));return x}
function blank(){return{paid:{},deleted:{},overrides:{},custom:[],version:APP.version}}
let state;try{state=JSON.parse(localStorage.getItem(KEY))||blank()}catch{state=blank()}
let applyingRemote=false,saveTimer;
function save(){localStorage.setItem(KEY,JSON.stringify(state));if(!applyingRemote&&window.pushCloudState){clearTimeout(saveTimer);saveTimer=setTimeout(()=>window.pushCloudState(state),300)}}
function recurring(r){const[id,name,category,start,day,amount,count,until]=r,d0=parse(start),out=[];if(count){for(let i=0;i<count;i++){const d=plusMonth(d0,i,day);out.push({id:`${id}-${iso(d)}`,name,category,date:iso(d),amount})}}else{const end=parse(until);for(let i=0;;i++){const d=plusMonth(d0,i,day);if(d>end)break;out.push({id:`${id}-${iso(d)}`,name,category,date:iso(d),amount})}}return out}
function payments(){let a=APP.once.map(([id,name,category,date,amount])=>({id,name,category,date,amount})).concat(APP.recur.flatMap(recurring),state.custom||[]);return a.filter(x=>!state.deleted[x.id]).map(x=>({...x,...(state.overrides[x.id]||{}),paid:!!state.paid[x.id]})).sort((a,b)=>a.date.localeCompare(b.date)||a.name.localeCompare(b.name,'tr'))}
const month=s=>s.slice(0,7);
function setView(id){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===id));if(id==='dashboard')renderDashboard();if(id==='payments')renderPayments();if(id==='debts')renderDebts()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>setView(b.dataset.view));
function renderDashboard(){const a=payments(),sum=a.reduce((s,x)=>s+Number(x.amount),0),paid=a.filter(x=>x.paid).reduce((s,x)=>s+Number(x.amount),0),monthly={};a.forEach(x=>monthly[month(x.date)]=(monthly[month(x.date)]||0)+Number(x.amount));kpiTotal.textContent=tl.format(sum);kpiPaid.textContent=tl.format(paid);kpiRemaining.textContent=tl.format(sum-paid);kpiAugust.textContent=tl.format(monthly['2026-08']||0);const keys=Object.keys(monthly).sort().slice(0,12),max=Math.max(1,...keys.map(k=>monthly[k]));monthlyBars.innerHTML=keys.map(k=>`<div class="bar-row"><span>${esc(fms.format(parse(k+'-01')))}</span><div class="bar-track"><div class="bar-fill" style="width:${monthly[k]/max*100}%"></div></div><span class="bar-value">${tl.format(monthly[k])}</span></div>`).join('');const up=a.filter(x=>!x.paid).slice(0,8);upcomingList.innerHTML=up.length?up.map(x=>`<div class="upcoming-row"><div><div class="payment-name">${esc(x.name)}</div><div class="meta">${fd.format(parse(x.date))} · ${esc(x.category)}</div></div><div class="amount">${tl.format(x.amount)}</div></div>`).join(''):'<div class="empty">Bekleyen ödeme yok.</div>'}
function fillFilters(){const a=payments(),cats=[...new Set(a.map(x=>x.category))].sort((a,b)=>a.localeCompare(b,'tr')),mons=[...new Set(a.map(x=>month(x.date)))].sort();categoryFilter.innerHTML='<option value="">Tüm kategoriler</option>'+cats.map(x=>`<option>${esc(x)}</option>`).join('');monthFilter.innerHTML='<option value="">Tüm aylar</option>'+mons.map(x=>`<option value="${x}">${esc(fm.format(parse(x+'-01')))}</option>`).join('')}
function filtered(){const q=searchInput.value.trim().toLocaleLowerCase('tr'),c=categoryFilter.value,s=statusFilter.value,m=monthFilter.value;return payments().filter(x=>(!q||x.name.toLocaleLowerCase('tr').includes(q))&&(!c||x.category===c)&&(!m||month(x.date)===m)&&(!s||(s==='paid'&&x.paid)||(s==='unpaid'&&!x.paid)))}
function renderPaymentSummary(a=filtered()){const all=payments(),sum=rows=>rows.reduce((total,x)=>total+Number(x.amount),0),filteredTotal=sum(a),allTotal=sum(all),active=[searchInput,categoryFilter,statusFilter,monthFilter].some(x=>x.value),difference=Math.max(0,allTotal-filteredTotal),allByCategory={},filteredByCategory={};all.forEach(x=>allByCategory[x.category]=(allByCategory[x.category]||0)+Number(x.amount));a.forEach(x=>filteredByCategory[x.category]=(filteredByCategory[x.category]||0)+Number(x.amount));filteredPaymentTotal.textContent=tl.format(filteredTotal);allPaymentTotal.textContent=tl.format(allTotal);visiblePaymentCount.textContent=String(a.length);paymentCountNote.textContent=`Toplam ${all.length} kayıt`;filteredPaymentNote.textContent=active?(difference?`Genel toplamdan ${tl.format(difference)} daha az`:'Genel toplamla aynı'):'Görüntülenen ödemeler';categoryTotalsNote.textContent=active?'Filtrelenen / genel':'Genel toplamlar';paymentCategoryTotals.innerHTML=Object.keys(allByCategory).sort((x,y)=>x.localeCompare(y,'tr')).map(category=>`<div class="payment-category-item"><span class="tag">${esc(category)}</span><div class="payment-category-values">${active?`${tl.format(filteredByCategory[category]||0)}<small>Genel: ${tl.format(allByCategory[category])}</small>`:tl.format(allByCategory[category])}</div></div>`).join('')}
function renderPayments(){const a=filtered();paymentList.innerHTML=a.length?a.map(x=>`<div class="payment-row ${x.paid?'paid':''}"><div><div>${fd.format(parse(x.date))}</div><div class="meta">${x.paid?'Ödendi':'Bekliyor'}</div></div><div><div class="payment-name">${esc(x.name)}</div></div><div class="category"><span class="tag">${esc(x.category)}</span></div><div class="amount">${tl.format(x.amount)}</div><div class="actions"><button onclick="togglePaid('${x.id}')">${x.paid?'Geri al':'Ödendi'}</button><button onclick="editPayment('${x.id}')">Düzenle</button><button onclick="deletePayment('${x.id}')">Sil</button></div></div>`).join(''):'<div class="empty">Kayıt bulunamadı.</div>'}
[searchInput,categoryFilter,statusFilter,monthFilter].forEach(x=>x.oninput=()=>{renderPayments();renderPaymentSummary()});
window.togglePaid=id=>{state.paid[id]=!state.paid[id];if(!state.paid[id])delete state.paid[id];save();renderAll()};
window.deletePayment=id=>{if(!confirm('Bu ödeme silinsin mi?'))return;const i=state.custom.findIndex(x=>x.id===id);if(i>=0)state.custom.splice(i,1);else state.deleted[id]=true;save();fillFilters();renderAll()};
function openModal(){modal.classList.add('open')}function close(){modal.classList.remove('open')}
addPayment.onclick=()=>{paymentForm.reset();editId.value='';formDate.value=iso(new Date);modalTitle.textContent='Yeni ödeme';openModal()};closeModal.onclick=close;modal.onclick=e=>{if(e.target===modal)close()};
window.editPayment=id=>{const x=payments().find(p=>p.id===id);if(!x)return;editId.value=id;formName.value=x.name;formCategory.value=x.category;formDate.value=x.date;formAmount.value=x.amount;modalTitle.textContent='Ödemeyi düzenle';openModal()};
paymentForm.onsubmit=e=>{e.preventDefault();const id=editId.value,v={name:formName.value.trim(),category:formCategory.value,date:formDate.value,amount:Number(formAmount.value)};if(!v.name||!v.date||!(v.amount>0))return;if(id){const i=state.custom.findIndex(x=>x.id===id);if(i>=0)state.custom[i]={...state.custom[i],...v};else state.overrides[id]=v}else state.custom.push({id:'custom-'+Date.now(),...v});save();close();fillFilters();renderAll();setView('payments')};
function renderDebts(){const groups={};APP.debts.forEach(([,c,n])=>groups[c]=(groups[c]||0)+n);const total=Object.values(groups).reduce((a,b)=>a+b,0);debtGrid.innerHTML=[...Object.entries(groups),['Toplam',total]].map(([k,v])=>`<article class="debt-card"><h3>${esc(k)}</h3><b>${tl.format(v)}</b></article>`).join('')+`<article class="panel" style="grid-column:1/-1"><h2>Borç kalemleri</h2>${APP.debts.map(([n,c,v])=>`<div class="upcoming-row"><div><div class="payment-name">${esc(n)}</div><div class="meta">${esc(c)}</div></div><div class="amount">${tl.format(v)}</div></div>`).join('')}</article>`}
function download(name,text,type){const b=new Blob([text],{type}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
exportJson.onclick=()=>download('metin-finans-yedek.json',JSON.stringify({state},null,2),'application/json');
exportCsv.onclick=()=>{const rows=[['Tarih','Ödeme','Kategori','Tutar','Durum'],...payments().map(x=>[x.date,x.name,x.category,String(x.amount).replace('.',','),x.paid?'Ödendi':'Bekliyor'])],csv='\ufeff'+rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n');download('metin-finans.csv',csv,'text/csv;charset=utf-8')};
importJson.onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const j=JSON.parse(await f.text());state=j.state||j;save();fillFilters();renderAll();alert('Yedek yüklendi.')}catch{alert('Dosya okunamadı.')}e.target.value=''};
window.applyRemoteState=s=>{if(!s)return;applyingRemote=true;state={...blank(),...s,version:APP.version};localStorage.setItem(KEY,JSON.stringify(state));fillFilters();renderAll();applyingRemote=false};window.getLocalAppState=()=>state;
function renderAll(){renderDashboard();renderPayments();renderPaymentSummary();renderDebts()}
fillFilters();renderAll();
